"""Project-authored native OmniCortex action and capability training data.

These are optimizer inputs, never runtime prompt text or answer keys.
"""

from typing import Any, Dict, List, Tuple

NATIVE_ACTION_EXAMPLES: List[Tuple[str, str]] = [('hi', 'talk'),
 ('hello', 'talk'),
 ('hey', 'talk'),
 ('hello, tell me what you notice', 'talk'),
 ('explain the relationship in ordinary language', 'talk'),
 ('read the selected file and inspect its structure', 'tool'),
 ('search the web for current primary sources', 'tool'),
 ('open the creativity workspace so I can visualize this idea', 'tool'),
 ('show me the imagination studio and gallery', 'tool'),
 ('move the pointer to the explicit coordinates I gave', 'tool'),
 ('take a native snapshot burst from the active live perception', 'tool'),
 ('make an image from this internal scene', 'imagine'),
 ('generate a short sound for this idea', 'imagine'),
 ('fork agents to investigate these independent parts', 'agent'),
 ('let another branch test this hypothesis', 'agent'),
 ('stay with this uncertainty and compute further', 'ponder'),
 ('consider the unresolved alternatives again', 'ponder'),
 ('pause internally before answering this difficult question', 'ponder'),
 ('reason through another recurrent pass before speaking', 'ponder'),
 ('quietly check this answer against the active evidence before speaking', 'ponder'),
 ('brainstorm several connected designs and let the strongest coherent one settle', 'ponder'),
 ('revise the proposed approach after testing its weak assumptions', 'ponder'),
 ('continue pondering because the last pass exposed an unresolved contradiction', 'ponder'),
 ('the answer is already clear and supported, so talk without unnecessary pondering', 'talk'),
 ('this simple greeting needs a natural reply rather than an internal compute loop', 'talk'),
 ('learn this dataset into the neural substrate', 'learn'),
 ('consolidate this experience into long term synapses', 'learn'),
 ('create and evaluate an improvement candidate', 'evolve'),
 ('test whether the improved learner improves itself', 'evolve'),
 ('search my visible conversation and action history for earlier evidence', 'tool'),
 ('inspect what I visibly said and did before deciding the next action', 'tool'),
 ('inspect which tools I can currently use before choosing an action', 'tool'),
 ('open the permissions workspace so access can be reviewed', 'tool'),
 ('stop the current activity', 'stop'),
 ('cancel and leave the state unchanged', 'stop')]

NATIVE_TOOL_TRAJECTORIES: List[Dict[str, Any]] = [{'toolId': 'web.search',
  'action': 'search',
  'utterance': 'search the web for current ternary neural kernels',
  'arguments': {'query': 'current ternary neural kernels'},
  'outcome': 'success',
  'result': {'sources': ['primary source']}},
 {'toolId': 'web.fetch',
  'action': 'fetch',
  'utterance': 'fetch https://example.org/paper',
  'arguments': {'url': 'https://example.org/paper'},
  'outcome': 'error',
  'result': {'status': 503}},
 {'toolId': 'browser.automation',
  'action': 'task',
  'utterance': 'open https://example.org and click `Documentation`',
  'arguments': {'url': 'https://example.org',
                'steps': [{'kind': 'click', 'selector': 'Documentation'}]},
  'outcome': 'success',
  'result': {'visible': True}},
 {'toolId': 'device.input',
  'action': 'move-pointer',
  'utterance': 'move the pointer to x 640 y 360',
  'arguments': {'x': 640, 'y': 360},
  'outcome': 'success',
  'result': {'audit': 'visible'}},
 {'toolId': 'device.input',
  'action': 'click',
  'utterance': 'click the right mouse button',
  'arguments': {'button': 'right'},
  'outcome': 'permission-denied',
  'result': {'wait': True}},
 {'toolId': 'device.input',
  'action': 'scroll',
  'utterance': 'scroll down 480',
  'arguments': {'deltaY': -480},
  'outcome': 'success',
  'result': {'audit': 'visible'}},
 {'toolId': 'device.input',
  'action': 'key-press',
  'utterance': 'press ctrl+shift+k',
  'arguments': {'key': 'k', 'modifiers': ['ctrl', 'shift']},
  'outcome': 'success',
  'result': {'audit': 'visible'}},
 {'toolId': 'device.input',
  'action': 'text',
  'utterance': 'type `explicit local text`',
  'arguments': {'text': 'explicit local text'},
  'outcome': 'permission-denied',
  'result': {'wait': True}},
 {'toolId': 'device.observe',
  'action': 'configure',
  'utterance': 'temporarily set live perception to detail at 1920 by 1080 and 12 fps for 8 seconds',
  'arguments': {'mode': 'detail', 'width': 1920, 'height': 1080, 'fps': 12, 'durationMs': 8000},
  'outcome': 'success',
  'result': {'temporary': True, 'reverted': True}},
 {'toolId': 'device.observe',
  'action': 'snapshot',
  'utterance': 'take a native snapshot burst of 3 frames every 250 ms',
  'arguments': {'resolutionMode': 'native', 'burstCount': 3, 'intervalMs': 250},
  'outcome': 'success',
  'result': {'framesAccepted': 3}},
 {'toolId': 'modality.imagine',
  'action': 'generate',
  'utterance': 'imagine an image from the active internal scene',
  'arguments': {'modality': 'image', 'fromAssemblies': True},
  'outcome': 'success',
  'result': {'artifact': 'image'}},
 {'toolId': 'studio.ui',
  'action': 'open-creativity',
  'utterance': 'open the creativity gallery',
  'arguments': {},
  'outcome': 'success',
  'result': {'workspace': 'creativity'}},
 {'toolId': 'studio.settings',
  'action': 'inspect-access',
  'utterance': 'inspect my current tool access before acting',
  'arguments': {},
  'outcome': 'success',
  'result': {'grantsChanged': False, 'approvalTimeoutSeconds': 30}},
 {'toolId': 'studio.settings',
  'action': 'open-permissions',
  'utterance': 'open the permissions workspace so I can ask for access',
  'arguments': {},
  'outcome': 'success',
  'result': {'workspace': 'tools', 'grantsChanged': False}},
 {'toolId': 'brain.history',
  'action': 'read',
  'utterance': 'show my last visible action result',
  'arguments': {'scope': 'visible', 'limit': 1},
  'outcome': 'success',
  'result': {'privateTraceIncluded': False}},
 {'toolId': 'brain.history',
  'action': 'search',
  'utterance': 'search my visible conversation for the earlier harbor answer',
  'arguments': {'query': 'harbor answer', 'scope': 'visible'},
  'outcome': 'success',
  'result': {'matches': 1, 'privateTraceIncluded': False}},
 {'toolId': 'agent.fork',
  'action': 'start',
  'utterance': 'fork an agent to test this independent hypothesis',
  'arguments': {'objective': 'test independent hypothesis'},
  'outcome': 'permission-denied',
  'result': {'wait': True}},
 {'toolId': 'source.self-modify',
  'action': 'propose',
  'utterance': 'propose an isolated improvement candidate',
  'arguments': {'candidateKind': 'substrate'},
  'outcome': 'success',
  'result': {'candidate': 'isolated'}},
 {'toolId': 'source.self-modify',
  'action': 'diff',
  'utterance': 'show the candidate diff',
  'arguments': {'candidate': 'isolated'},
  'outcome': 'success',
  'result': {'changed': True}},
 {'toolId': 'source.self-modify',
  'action': 'test',
  'utterance': 'test the isolated candidate against immutable evaluations',
  'arguments': {'candidate': 'isolated'},
  'outcome': 'success',
  'result': {'passed': True}},
 {'toolId': 'source.self-modify',
  'action': 'promote',
  'utterance': 'promote the passing candidate',
  'arguments': {'candidate': 'isolated'},
  'outcome': 'permission-denied',
  'result': {'wait': True}},
 {'toolId': 'source.self-modify',
  'action': 'rollback',
  'utterance': 'roll back the regressed candidate',
  'arguments': {'candidate': 'isolated'},
  'outcome': 'success',
  'result': {'restored': True}}]

NATIVE_TOOL_NEGATIVE_EXAMPLES: List[Dict[str, str]] = [{'utterance': 'hello', 'reason': 'ordinary conversation needs no external action'},
 {'utterance': 'what is two plus two', 'reason': 'known simple answer needs no tool'},
 {'utterance': 'write something somewhere', 'reason': 'missing explicit path and content'},
 {'utterance': 'open a website', 'reason': 'missing explicit safe URL'},
 {'utterance': 'type something for me', 'reason': 'device text requires explicitly quoted content'},
 {'utterance': 'move the mouse somewhere',
  'reason': 'device movement requires explicit coordinates'}]
