"""No-context, model-generated acceptance rules for multi-stage memory.

This is a test harness, not another memory implementation.  Focused path tests
feed it measurements from the real brain after the protected integration is
complete. Exact sequence decoding can establish a memory mechanism, but cannot
stand in for an answer generated by learned cortical weights after restart.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from typing import Dict, Literal, Optional, Tuple


MemoryPath = Literal[
    "messy-chat",
    "direct-learn-experience",
    "typed-jsonl",
    "plain-file",
    "parquet-text-row",
    "web-crawl",
]
Representation = Literal["detailed", "statistical"]
ExactMode = Literal["adjacent-temporal", "typed-target"]


@dataclass(frozen=True)
class MemoryPathSpec:
    path: MemoryPath
    entrypoint: str
    exact_mode: ExactMode
    coverage_required: bool
    exact_condition: str
    semantic_acceptance: str


@dataclass(frozen=True)
class MemoryPathFixture:
    experience: str
    query: str
    expected_exact_text: str
    unrelated_control: str
    declared_response: str = ""


PATH_SPECS: Dict[MemoryPath, MemoryPathSpec] = {
    "messy-chat": MemoryPathSpec(
        path="messy-chat",
        entrypoint="AdaptiveBrain.chat(user experience)",
        exact_mode="adjacent-temporal",
        coverage_required=False,
        exact_condition=(
            "detailed episode with an eligible non-question segment or a "
            "later query containing a learned temporal/alias cue"
        ),
        semantic_acceptance=(
            "learned target ranks above a control and the restarted model "
            "generates a correct answer"
        ),
    ),
    "direct-learn-experience": MemoryPathSpec(
        path="direct-learn-experience",
        entrypoint="AdaptiveBrain.learn_experience(text)",
        exact_mode="adjacent-temporal",
        coverage_required=False,
        exact_condition=(
            "detailed episode with an eligible non-question segment or a "
            "later query containing a learned temporal/alias cue"
        ),
        semantic_acceptance=(
            "learned target ranks above a control and the restarted model "
            "generates a correct answer"
        ),
    ),
    "typed-jsonl": MemoryPathSpec(
        path="typed-jsonl",
        entrypoint="DatasetRecord typed-dialogue -> _apply_supervised_dialogue",
        exact_mode="typed-target",
        coverage_required=True,
        exact_condition=(
            "resource plan retained exact dialogue sequences and the query "
            "contains the taught human cue"
        ),
        semantic_acceptance=(
            "compact typed rows update the statistical field; restarted model "
            "output still needs an answer-quality check"
        ),
    ),
    "plain-file": MemoryPathSpec(
        path="plain-file",
        entrypoint="ingest text record -> generic multi-stage experience",
        exact_mode="adjacent-temporal",
        coverage_required=True,
        exact_condition=(
            "detailed record with an eligible non-question segment and a "
            "learned full-segment, alias, or temporal cue"
        ),
        semantic_acceptance=(
            "single/compact records need retrieval ranking and a correct "
            "restarted model answer"
        ),
    ),
    "parquet-text-row": MemoryPathSpec(
        path="parquet-text-row",
        entrypoint="Parquet text row -> generic multi-stage experience",
        exact_mode="adjacent-temporal",
        coverage_required=True,
        exact_condition=(
            "detailed row with an eligible non-question segment and a learned "
            "full-segment, alias, or temporal cue"
        ),
        semantic_acceptance=(
            "single/compact rows need retrieval ranking and a correct "
            "restarted model answer"
        ),
    ),
    "web-crawl": MemoryPathSpec(
        path="web-crawl",
        entrypoint="accepted crawl text -> ingest -> generic multi-stage experience",
        exact_mode="adjacent-temporal",
        coverage_required=True,
        exact_condition=(
            "non-quarantined detailed transformed text with an eligible "
            "non-question segment and a learned segment, alias, or temporal cue"
        ),
        semantic_acceptance=(
            "quarantine is not learning; accepted single/compact pages need "
            "retrieval ranking and a correct restarted model answer"
        ),
    ),
}

# Deliberately varied, colloquial inputs.  Their only exact structure is typed
# supervision or ordinary sentence order; no shared "X is Y" fact template is
# available to select the memory pathway.
PATH_FIXTURES: Dict[MemoryPath, MemoryPathFixture] = {
    "messy-chat": MemoryPathFixture(
        experience=(
            "So, um... I shoved the cobalt ticket under the wobbly lamp after "
            "lunch! Where did I shove the cobalt ticket? Keep it brief."
        ),
        query="Where did I shove the cobalt ticket? Please answer briefly.",
        expected_exact_text=(
            "I shoved the cobalt ticket under the wobbly lamp after lunch!"
        ),
        unrelated_control="A violin was tuned beside the river.",
    ),
    "direct-learn-experience": MemoryPathFixture(
        experience=(
            "No tidy database row here—the blue chalk went inside the dented tin. "
            "Where did the blue chalk go?"
        ),
        query="Where did the blue chalk go? Answer from the earlier experience.",
        expected_exact_text=(
            "No tidy database row here—the blue chalk went inside the dented tin."
        ),
        unrelated_control="A silver kite crossed the courtyard.",
    ),
    "typed-jsonl": MemoryPathFixture(
        experience="Could you repeat the odd phrase I supplied?",
        query="Could you repeat the odd phrase I supplied?",
        expected_exact_text="violet canoe seventeen",
        unrelated_control="winter orchard ninety",
        declared_response="violet canoe seventeen",
    ),
    "plain-file": MemoryPathFixture(
        experience=(
            "Morning notes wandered a bit. The brass key rested beneath the fern. "
            "Where did the brass key rest?"
        ),
        query="Where did the brass key rest? Use the note.",
        expected_exact_text="The brass key rested beneath the fern.",
        unrelated_control="The noon train stopped beside a quarry.",
    ),
    "parquet-text-row": MemoryPathFixture(
        experience=(
            "A hurried inventory followed. We tucked the linen map behind the red "
            "thermos. Where did we tuck the linen map?"
        ),
        query="Where did we tuck the linen map? Use the inventory row.",
        expected_exact_text=(
            "We tucked the linen map behind the red thermos."
        ),
        unrelated_control="Two lanterns hung over the station door.",
    ),
    "web-crawl": MemoryPathFixture(
        experience=(
            "Field journal update. Someone left the cedar paddle by the cracked "
            "fountain. Where was the cedar paddle left?"
        ),
        query="Where was the cedar paddle left? Use the accepted page.",
        expected_exact_text=(
            "Someone left the cedar paddle by the cracked fountain."
        ),
        unrelated_control="Clouds gathered above a distant radio mast.",
    ),
}


@dataclass(frozen=True)
class GeneratedAnswerEvidence:
    """Measurements from one real post-restart chat, not sequence decoding."""

    expected_text: str
    generated_text: str
    backend: str
    generated_token_count: int
    answer_quality_passed: bool
    fresh_attention_committed: bool
    fresh_attention_epoch: int
    worker_restarted: bool
    cortical_checksum_before_learning: str
    cortical_checksum_after_learning: str
    cortical_checksum_after_restart: str
    training_steps_before: int
    training_steps_after: int
    raw_text_retrieved: bool
    raw_token_ids_retrieved: bool


@dataclass(frozen=True)
class PathObservation:
    path: MemoryPath
    representation: Representation
    segment_count: int
    query_contains_learned_cue: bool
    typed_target_present: bool
    attributable_source: bool
    accepted_for_learning: bool
    coverage_complete: Optional[bool]
    grammar_specific_gate_used: bool
    statistical_updates: int
    semantic_target_present: bool
    semantic_target_score: float
    semantic_control_score: float
    statistical_forward_precision: str
    recent_dialogue_tokens: int
    prior_prompt_text_expanded: bool
    raw_source_text_injected: bool
    exact_eligible_segments: int = 0
    answer: Optional[GeneratedAnswerEvidence] = None


@dataclass(frozen=True)
class AcceptanceResult:
    path: MemoryPath
    expected_level: Literal["exact-generated", "semantic-generated"]
    passed: bool
    failures: Tuple[str, ...]


def expected_acceptance_level(
    observation: PathObservation,
) -> Literal["exact-generated", "semantic-generated"]:
    spec = PATH_SPECS[observation.path]
    if observation.representation != "detailed":
        return "semantic-generated"
    if not observation.query_contains_learned_cue:
        return "semantic-generated"
    if spec.exact_mode == "typed-target":
        return (
            "exact-generated"
            if observation.typed_target_present
            else "semantic-generated"
        )
    return (
        "exact-generated"
        if observation.exact_eligible_segments > 0
        else "semantic-generated"
    )


def assess_path_observation(observation: PathObservation) -> AcceptanceResult:
    """Check necessary evidence; a synthetic matrix pass is not a live pass."""

    spec = PATH_SPECS[observation.path]
    level = expected_acceptance_level(observation)
    failures = []

    if not observation.attributable_source:
        failures.append("learning source is not attributable")
    if not observation.accepted_for_learning:
        failures.append("source was quarantined, rejected, or otherwise not learned")
    if spec.coverage_required and observation.coverage_complete is not True:
        failures.append("source traversal/record coverage is incomplete")
    if observation.grammar_specific_gate_used:
        failures.append("a grammar-specific fact gate selected the memory path")
    if observation.statistical_updates < 1:
        failures.append("the generic statistical association stage did not update")
    if not observation.semantic_target_present:
        failures.append("the learned semantic target was not retrieved")
    if not (
        math.isfinite(observation.semantic_target_score)
        and math.isfinite(observation.semantic_control_score)
        and observation.semantic_target_score > observation.semantic_control_score
    ):
        failures.append("semantic target did not outrank the unrelated control")
    if observation.statistical_forward_precision != "exact ternary {-1,0,+1}":
        failures.append("statistical recall did not use exact ternary forwards")

    # The current query is allowed. Prior conversation/source prose is not.
    if observation.recent_dialogue_tokens != 0:
        failures.append("prior recent-dialogue context was still present")
    if observation.prior_prompt_text_expanded:
        failures.append("prior prompt text was expanded into the query")
    if observation.raw_source_text_injected:
        failures.append("raw source text was injected during recall")

    answer = observation.answer
    if answer is None:
        failures.append("no model-generated answer after Fresh and worker restart")
    else:
        if not answer.fresh_attention_committed or answer.fresh_attention_epoch < 1:
            failures.append("Fresh attention did not commit before the answer")
        if not answer.worker_restarted:
            failures.append("answer was not generated after a worker restart")
        if answer.backend != "mutable-omni-decoder":
            failures.append("answer did not come from a model generation backend")
        if answer.generated_token_count < 1 or not answer.generated_text.strip():
            failures.append("model produced no answer tokens")
        checksums = (
            answer.cortical_checksum_before_learning,
            answer.cortical_checksum_after_learning,
            answer.cortical_checksum_after_restart,
        )
        if not all(re.fullmatch(r"[0-9a-f]{64}", value) for value in checksums):
            failures.append("cortical weight checksums are missing or invalid")
        elif (
            answer.cortical_checksum_before_learning
            == answer.cortical_checksum_after_learning
        ):
            failures.append("learning did not change cortical weights")
        elif (
            answer.cortical_checksum_after_learning
            != answer.cortical_checksum_after_restart
        ):
            failures.append("learned cortical weights did not survive restart")
        if answer.training_steps_after <= answer.training_steps_before:
            failures.append("no cortical training step was committed")
        if answer.raw_text_retrieved or answer.raw_token_ids_retrieved:
            failures.append("answer consulted retained text or raw token ids")
        if not answer.answer_quality_passed:
            failures.append("generated answer failed its answer-quality check")
        if level == "exact-generated" and (
            not answer.expected_text
            or answer.generated_text != answer.expected_text
        ):
            failures.append("generated response was not an exact content match")

    return AcceptanceResult(
        path=observation.path,
        expected_level=level,
        passed=not failures,
        failures=tuple(failures),
    )


__all__ = [
    "AcceptanceResult",
    "GeneratedAnswerEvidence",
    "MemoryPathSpec",
    "MemoryPathFixture",
    "PATH_FIXTURES",
    "PATH_SPECS",
    "PathObservation",
    "assess_path_observation",
    "expected_acceptance_level",
]
